### ISSUE TITLE
I tried it on 8 L4OS (GPU 45GB in RAM), it failed with OOM error. 

### ISSUE THREAD

**Issue by jzkunlun** [KellerJordan/modded-nanogpt#12]
[rank0]: Traceback (most recent call last):

[rank0]:   File "/home/cloud-user/git/modded-nanogpt/train_gpt2.py", line 502, in <module>

[rank0]:     loss.backward() # just sync on the last step

[rank0]:     ^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_tensor.py", line 521, in backward

[rank0]:     torch.autograd.backward(

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/autograd/__init__.py", line 289, in backward

[rank0]:     _engine_run_backward(

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backwa

rd

[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/autograd/function.py", line 306, in apply

[rank0]:     return user_fn(self, *args)

[rank0]:            ^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line

 1861, in backward

[rank0]:     out = call_compiled_backward()

[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line

 1809, in call_compiled_backward

[rank0]:     out = call_func_at_runtime_with_args(

[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/utils.py", line 120, in ca

ll_func_at_runtime_with_args

[rank0]:     out = normalize_as_list(f(args))

[rank0]:                             ^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn

[rank0]:     return fn(*args, **kwargs)

[rank0]:            ^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/codecache.py", line 1131, in __call__

[rank0]:     return self.current_callable(inputs)

[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 944, in run

[rank0]:     return model(new_inputs)

[rank0]:            ^^^^^^^^^^^^^^^^^

[rank0]:   File "/tmp/torchinductor_cloud-user/jq/cjqn3jolpzaax2mauq2p4xteeedryoltbgsvyc5xue44bcjycjxo.py", line 204, in call

[rank0]:     triton_poi_fused_nll_loss_backward_nll_loss_forward_1.run(primals_2, buf0, 65536, grid=grid(65536), stream=stream0

)

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 820, 

in run

[rank0]:     self.autotune_to_one_config(*args, grid=grid, **kwargs)

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 718, 

in autotune_to_one_config

[rank0]:     timings = self.benchmark_all_configs(*args, **kwargs)

[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper

[rank0]:     r = func(*args, **kwargs)

[rank0]:         ^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 694, 

in benchmark_all_configs

[rank0]:     launcher: self.bench(launcher, *args, **kwargs)

[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 665, 

in bench

[rank0]:     return do_bench_gpu(kernel_call, rep=40, fast_flush=True)

[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/runtime_utils.py", line 113, in d

o_bench_gpu

[rank0]:     return triton_do_bench(*args, **kwargs)[0]

[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/triton/testing.py", line 103, in do_bench

[rank0]:     fn()

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 657, 

in kernel_call

[rank0]:     cloned_args, cloned_kwargs = self.clone_args(*args, **kwargs)

[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 677, 

in clone_args

[rank0]:     cloned_args.append(clone_preserve_strides(arg))

[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]:   File "/home/cloud-user/python/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 889, in clone_preser

ve_strides

[rank0]:     buffer = torch.as_strided(x, (needed_size,), (1,)).clone()

[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.28 GiB. GPU 0 has a total capacity of 44.42 GiB of wh

ich 2.45 GiB is free. Including non-PyTorch memory, this process has 41.96 GiB memory in use. Of the allocated memory 41.28 GiB

 is allocated by PyTorch, and 38.68 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try

 setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (ht

tps://[pytorch.org/docs/stable/notes/cuda.html#environment-variables](http://pytorch.org/docs/stable/notes/cuda.html#environment-variables))

**Comment by KellerJordan** [comment]
try reducing the [per device batch size](https://github.com/KellerJordan/modded-nanogpt/blob/e5b254f5628387a0ac1b10787cd833e6dbbcfcc8/train_gpt2.py#L335) to 32

**Comment by jzkunlun** [comment]
it worked,  thanks,

**Comment by jzkunlun** [comment]
changing batchsize to 32 made working

**Comment by jzkunlun** [comment]
close it
