### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by HaiFengZeng** [KellerJordan/modded-nanogpt#14]
how to do inference?

**Comment by josephflowers-ra** [comment]
Did you post the final models?

**Comment by lemonteaa** [comment]
I did a straight run of this repo, unmodified (except for the obvious run parameters), on the cloud using one L40S. Results with the checkpoints/log/final model/inference code/online demo is posted at huggingface here: https://huggingface.co/lemonteaa/nanogpt-speedrun

(No claim that the codes are bug free though as I just ask AI to code it up quickly with some manual coding on the non core part)

**Comment by HaiFengZeng** [comment]
I think [gpt-fast](https://github.com/pytorch-labs/gpt-fast) will do a lot of help
