### ISSUE TITLE
We don't have 8xH100, how about opening a new track?

### ISSUE THREAD

**Issue by Triang-jyed-driung** [KellerJordan/modded-nanogpt#18]
Hi, 
I really love this project and am willing to participate. This project has shown how powerful new optimization techniques are.
However, H100 have been banned in China from the day it's out on the market. We have 4090s and H800s, but machines are shared across users.
Can we open a new track for less GPUs (for example 1x4090)? The rationales:
1. Affordable time: We can afford having more time to train these models. Since the first record is 45 mins, we can wait for approximately 45 mins * 8 = 6 hours on a single GPU. 
2. Broader participation: anyone with one decent GPU can participate, while 8xH100 is certainly too expensive for individual developers.
3. Startup time: Since the records are reaching 8 minutes, the start-up time is no longer negligible (usually, training at the first few steps is significantly slower than remaining steps).

**Comment by KellerJordan** [comment]
Hey, thanks. I would be happy for competitors with one GPU to participate. The current record can be run on a single GPU just by changing nproc_per_node=1.

If a competitor is interested in developing their speedrun on a single GPU, then the cost of doing the final timed run on 8xH100 is about $3.2 at current market rates for rented instances. (maybe $5 including the startup time of the instance)

I think this is pretty accessible. I'd also be happy to execute a submitted run/code on 8xH100 myself, if I think it looks promising based on single-GPU timings.

Hope that helps!

**Comment by KellerJordan** [comment]
Yes, it's a rule for the speedrun that the number of active parameters per token must be 124M
