### ISSUE TITLE
did you forget to call torch.distributed.all_reduce function in train_gpt2.py

### ISSUE THREAD

**Issue by zhangfaen** [KellerJordan/modded-nanogpt#2]
did you forget to call torch.distributed.all_reduce function in train_gpt2.py ?

**Comment by KellerJordan** [comment]
If you wrap in DDP it's automatic with the backward pass

**Comment by KellerJordan** [comment]
Oh I see what you mean, regarding the loss logging. You're right.

**Comment by zhangfaen** [comment]
Yea, to log exact loss, you may need that call.
