### ISSUE TITLE
Why limit FlexAttention to B=1?

### ISSUE THREAD

**Issue by ViktorooReps** [KellerJordan/modded-nanogpt#34]
https://github.com/KellerJordan/modded-nanogpt/blob/master/train_gpt2.py#L189

Am I understanding this correctly that instead of scaling batch size, you just scale sequence length and it is more or less the same (but better really) due to window attention?

**Comment by iiLaurens** [comment]
A batch of sequences is technically equivalent to the concatenation of all those sequences, and then limiting self-attention to not cross subsequence boundaries. You can see it visualized in this blog under document masking/jagged sequences: https://pytorch.org/blog/flexattention/#document-maskingjagged-sequences

**Comment by ViktorooReps** [comment]
Makes sense! Thanks

**Comment by lhallee** [comment]
This doesn't quite get at WHY though. I guess we don't compute over pad tokens which saves flops on each batch?

**Comment by ViktorooReps** [comment]
In my understanding, it is always better to have a fully contextualized token, so there is simply no reason to set B>1 and potentially chop the document into smaller sequences, rather than using B=1 and as large sequence size as you can afford, given your batch size.

It would be nice though to have some academic proof to this
