### ISSUE TITLE
 RoPE has precision errors when used with BFloat16 

### ISSUE THREAD

**Issue by banyan-god** [KellerJordan/modded-nanogpt#39]
The current implementation converts trigonometric values (cos_cached and sin_cached) to bfloat16, which introduces significant precision issues. This degrades the relative positional encoding properties of RoPE, particularly in **long-context** scenarios, as numerical errors accumulate. Using float32 for trigonometric values resolves this issue while maintaining RoPE's effectiveness for long-range dependencies.

Suggested Fix: Replace .bfloat16() with .float() for cos_cached and sin_cached to ensure precision without affecting overall performance

References

- https://www.reddit.com/r/LocalLLaMA/comments/1h26gbp/rope_has_precision_errors_when_used_with_bfloat16/
- https://github.com/huggingface/transformers/pull/29285

**Comment by KellerJordan** [comment]
does this actually impact the final performance? That's the only thing I care about in this repo

**Comment by banyan-god** [comment]
Interestingly loss didn't improve at the same time it didn't take longer either. May be a comment might suffice if it interests you.
[514e8a53-74e0-4d77-a61e-53a416f3ec3a.txt](https://github.com/user-attachments/files/17966621/514e8a53-74e0-4d77-a61e-53a416f3ec3a.txt)

**Comment by banyan-god** [comment]
Well it did improve the loss 

- float step:1750/1750 val_loss:3.2783 train_time:1889410ms step_avg:1085.87ms
- bfloat16 step:1750/1750 val_loss:3.2833 train_time:1887346ms step_avg:1084.68ms

**Comment by KellerJordan** [comment]
I ran it a few times and didn't see a perf impact (either wallclock or loss), but it does seem maybe(?) more correct. so added.
